name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: https://registry.yarnpkg.com/

    - name: Install dependencies
      run: yarn install

    - name: Check EsLint Errors 
      run: yarn lint

    - name: Build 
      run: yarn build